# Generated by Django 5.2.7 on 2025-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor_Info",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Registration_number", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("Qulification", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("Experiance", models.IntegerField()),
                ("timing", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("gender", models.CharField(max_length=10)),
                ("Hospital_address", models.TextField()),
            ],
        ),
    ]
