# Generated by Django 5.2.7 on 2025-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient_Info",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("contact", models.CharField(max_length=15)),
                ("disease", models.CharField(max_length=100)),
                ("admitted_date", models.DateField()),
            ],
        ),
    ]
